/*
 * Created on 2010-10-14, 22:45:00
 * By Yichao Yu
 */

package simulator.console;
import simulator.controller.*;
import simulator.interfaces.*;

/** 
 * Class SimulatorConsole
 * Simulator's console UI. This is also the main method of the simulator.
 * The console UI part of this file is generated by NetBeans IDE. Just place the items on
 * the frames or panels, then it automatically generated the code.
 * 
 * Up to now, we start the application(simulator), and press the power button,
 * then the simulator will start a new thread to run a Controller object.
 * That object instance will communicate with the console UI and response to the UI events
 * to do the simulation task.
 * 
 * The simulator has a debug mode, in which we can execute the instruction step by step.
 * And display the contents of several outer registers to know how the machine is running.
 * 
 * Also, on the console, there is a printer and a keyboard as I/O devices.
 *                          
 * @author Yichao Yu
 * @version 10-15-2010
 * @see simulator.controller
 * @since JDK 1.6
 */
public class SimulatorConsole extends javax.swing.JFrame {
	
	/**
	 * reset of outer register monitor to zero.
	 */
	private void resetAll() {
		MARvalue.setText("000000000000000000000000");
		MBRvalue.setText("000000000000000000000000");
        GPR0value.setText("000000000000000000000000");
        GPR1value.setText("000000000000000000000000");
        GPR2value.setText("000000000000000000000000");
        GPR3value.setText("000000000000000000000000");
        PCvalue.setText("000000000000000000000000");
        stepButton.setEnabled(true);
        Printervalue.setText("");
        Printervalue.setEditable(false);
	}
	
	/**
	 * set of outer register monitors to the current value of corresponding registers.
	 */
	private void setAll() {
		MARvalue.setText(OutregsINF.getMAR().getStr());
        MBRvalue.setText(OutregsINF.getMBR().getStr());
        GPR0value.setText(GrINF.getR0().getStr());
        GPR1value.setText(GrINF.getR1().getStr());
        GPR2value.setText(GrINF.getR2().getStr());
        GPR3value.setText(GrINF.getR3().getStr());
        PCvalue.setText(PcINF.getPc().getStr());
        Printervalue.setText(DevicesINF.showPrinter());
	}
	
    /** Creates new form SimulatorConsole */
    public SimulatorConsole() {
        initComponents();
        resetAll();
    }

    private void initComponents() {

    	powerButton = new javax.swing.JToggleButton();
        stepButton = new javax.swing.JButton();
        MAR = new javax.swing.JPanel();
        MARvalue = new javax.swing.JLabel();
        MBR = new javax.swing.JPanel();
        MBRvalue = new javax.swing.JLabel();
        GPR0 = new javax.swing.JPanel();
        GPR0value = new javax.swing.JLabel();
        GPR1 = new javax.swing.JPanel();
        GPR1value = new javax.swing.JLabel();
        GPR2 = new javax.swing.JPanel();
        GPR2value = new javax.swing.JLabel();
        GPR3 = new javax.swing.JPanel();
        GPR3value = new javax.swing.JLabel();
        debugButton = new javax.swing.JToggleButton();
        PC = new javax.swing.JPanel();
        PCvalue = new javax.swing.JLabel();
        printPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Printervalue = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        buttonA = new javax.swing.JButton();
        buttonS = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        buttonF = new javax.swing.JButton();
        buttonG = new javax.swing.JButton();
        buttonH = new javax.swing.JButton();
        buttonJ = new javax.swing.JButton();
        buttonK = new javax.swing.JButton();
        buttonL = new javax.swing.JButton();
        buttonQ = new javax.swing.JButton();
        buttonO = new javax.swing.JButton();
        buttonW = new javax.swing.JButton();
        buttonE = new javax.swing.JButton();
        buttonR = new javax.swing.JButton();
        buttonT = new javax.swing.JButton();
        buttonY = new javax.swing.JButton();
        buttonU = new javax.swing.JButton();
        buttonI = new javax.swing.JButton();
        buttonZ = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonV = new javax.swing.JButton();
        buttonB = new javax.swing.JButton();
        buttonM = new javax.swing.JButton();
        buttonP = new javax.swing.JButton();
        buttonNum9 = new javax.swing.JButton();
        buttonNum1 = new javax.swing.JButton();
        buttonNum4 = new javax.swing.JButton();
        buttonNum5 = new javax.swing.JButton();
        buttonNum2 = new javax.swing.JButton();
        buttonNum3 = new javax.swing.JButton();
        buttonNum8 = new javax.swing.JButton();
        buttonNum7 = new javax.swing.JButton();
        buttonNum0 = new javax.swing.JButton();
        buttonNum6 = new javax.swing.JButton();
        buttonN = new javax.swing.JButton();
        buttonSpace = new javax.swing.JButton();
        buttonShift = new javax.swing.JToggleButton();
        buttonEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        powerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("off.png"))); // NOI18N
        powerButton.setRolloverEnabled(false);
        powerButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("on.png"))); // NOI18N
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });

        stepButton.setText("STEP");
        stepButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stepButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        MAR.setBorder(javax.swing.BorderFactory.createTitledBorder("MAR"));

        MARvalue.setText("000000000000000000000000");

        javax.swing.GroupLayout MARLayout = new javax.swing.GroupLayout(MAR);
        MAR.setLayout(MARLayout);
        MARLayout.setHorizontalGroup(
            MARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MARLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MARvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MARLayout.setVerticalGroup(
            MARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MARLayout.createSequentialGroup()
                .addComponent(MARvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MBR.setBorder(javax.swing.BorderFactory.createTitledBorder("MBR"));

        MBRvalue.setText("000000000000000000000000");

        javax.swing.GroupLayout MBRLayout = new javax.swing.GroupLayout(MBR);
        MBR.setLayout(MBRLayout);
        MBRLayout.setHorizontalGroup(
            MBRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MBRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MBRvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MBRLayout.setVerticalGroup(
            MBRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MBRLayout.createSequentialGroup()
                .addComponent(MBRvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR0.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 0"));

        GPR0value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR0Layout = new javax.swing.GroupLayout(GPR0);
        GPR0.setLayout(GPR0Layout);
        GPR0Layout.setHorizontalGroup(
            GPR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR0value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR0Layout.setVerticalGroup(
            GPR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR0Layout.createSequentialGroup()
                .addComponent(GPR0value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR1.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 1"));

        GPR1value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR1Layout = new javax.swing.GroupLayout(GPR1);
        GPR1.setLayout(GPR1Layout);
        GPR1Layout.setHorizontalGroup(
            GPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR1value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR1Layout.setVerticalGroup(
            GPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR1Layout.createSequentialGroup()
                .addComponent(GPR1value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR2.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 2"));

        GPR2value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR2Layout = new javax.swing.GroupLayout(GPR2);
        GPR2.setLayout(GPR2Layout);
        GPR2Layout.setHorizontalGroup(
            GPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR2value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR2Layout.setVerticalGroup(
            GPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR2Layout.createSequentialGroup()
                .addComponent(GPR2value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR3.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 3"));

        GPR3value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR3Layout = new javax.swing.GroupLayout(GPR3);
        GPR3.setLayout(GPR3Layout);
        GPR3Layout.setHorizontalGroup(
            GPR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR3value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR3Layout.setVerticalGroup(
            GPR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR3Layout.createSequentialGroup()
                .addComponent(GPR3value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        debugButton.setText("Debug Mode Off");
        debugButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        debugButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        debugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugButtonActionPerformed(evt);
            }
        });

        PC.setBorder(javax.swing.BorderFactory.createTitledBorder("PC"));

        PCvalue.setText("000000000000000000000000");

        javax.swing.GroupLayout PCLayout = new javax.swing.GroupLayout(PC);
        PC.setLayout(PCLayout);
        PCLayout.setHorizontalGroup(
            PCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PCLayout.setVerticalGroup(
            PCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCLayout.createSequentialGroup()
                .addComponent(PCvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        printPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Printer"));

        Printervalue.setColumns(20);
        Printervalue.setRows(5);
        jScrollPane1.setViewportView(Printervalue);

        javax.swing.GroupLayout printPanelLayout = new javax.swing.GroupLayout(printPanel);
        printPanel.setLayout(printPanelLayout);
        printPanelLayout.setHorizontalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        printPanelLayout.setVerticalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("KeyBoard"));

        buttonA.setText("A");
        buttonA.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAActionPerformed(evt);
            }
        });

        buttonS.setText("S");
        buttonS.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSActionPerformed(evt);
            }
        });

        buttonD.setText("D");
        buttonD.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDActionPerformed(evt);
            }
        });

        buttonF.setText("F");
        buttonF.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFActionPerformed(evt);
            }
        });

        buttonG.setText("G");
        buttonG.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGActionPerformed(evt);
            }
        });

        buttonH.setText("H");
        buttonH.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHActionPerformed(evt);
            }
        });

        buttonJ.setText("J");
        buttonJ.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJActionPerformed(evt);
            }
        });

        buttonK.setText("K");
        buttonK.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKActionPerformed(evt);
            }
        });

        buttonL.setText("L");
        buttonL.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLActionPerformed(evt);
            }
        });

        buttonQ.setText("Q");
        buttonQ.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQActionPerformed(evt);
            }
        });

        buttonO.setText("O");
        buttonO.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOActionPerformed(evt);
            }
        });

        buttonW.setText("W");
        buttonW.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWActionPerformed(evt);
            }
        });

        buttonE.setText("E");
        buttonE.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEActionPerformed(evt);
            }
        });

        buttonR.setText("R");
        buttonR.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRActionPerformed(evt);
            }
        });

        buttonT.setText("T");
        buttonT.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTActionPerformed(evt);
            }
        });

        buttonY.setText("Y");
        buttonY.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYActionPerformed(evt);
            }
        });

        buttonU.setText("U");
        buttonU.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUActionPerformed(evt);
            }
        });

        buttonI.setText("I");
        buttonI.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIActionPerformed(evt);
            }
        });

        buttonZ.setText("Z");
        buttonZ.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZActionPerformed(evt);
            }
        });

        buttonX.setText("X");
        buttonX.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXActionPerformed(evt);
            }
        });

        buttonC.setText("C");
        buttonC.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonV.setText("V");
        buttonV.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVActionPerformed(evt);
            }
        });

        buttonB.setText("B");
        buttonB.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBActionPerformed(evt);
            }
        });

        buttonM.setText("M");
        buttonM.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMActionPerformed(evt);
            }
        });

        buttonP.setText("P");
        buttonP.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPActionPerformed(evt);
            }
        });

        buttonNum9.setText("9");
        buttonNum9.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum9ActionPerformed(evt);
            }
        });

        buttonNum1.setText("1");
        buttonNum1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum1ActionPerformed(evt);
            }
        });

        buttonNum4.setText("4");
        buttonNum4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum4ActionPerformed(evt);
            }
        });

        buttonNum5.setText("5");
        buttonNum5.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum5ActionPerformed(evt);
            }
        });

        buttonNum2.setText("2");
        buttonNum2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum2ActionPerformed(evt);
            }
        });

        buttonNum3.setText("3");
        buttonNum3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum3ActionPerformed(evt);
            }
        });

        buttonNum8.setText("8");
        buttonNum8.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum8ActionPerformed(evt);
            }
        });

        buttonNum7.setText("7");
        buttonNum7.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum7ActionPerformed(evt);
            }
        });

        buttonNum0.setText("0");
        buttonNum0.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum0ActionPerformed(evt);
            }
        });

        buttonNum6.setText("6");
        buttonNum6.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNum6ActionPerformed(evt);
            }
        });

        buttonN.setText("N");
        buttonN.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNActionPerformed(evt);
            }
        });

        buttonSpace.setText("Space");
        buttonSpace.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpaceActionPerformed(evt);
            }
        });

        buttonShift.setText("Shift");
        buttonShift.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShiftActionPerformed(evt);
            }
        });

        buttonEnter.setText("Enter");
        buttonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonW, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonShift, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonX, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonG, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNum1)
                    .addComponent(buttonNum2)
                    .addComponent(buttonNum3)
                    .addComponent(buttonNum4)
                    .addComponent(buttonNum5)
                    .addComponent(buttonNum7)
                    .addComponent(buttonNum8)
                    .addComponent(buttonNum9)
                    .addComponent(buttonNum0)
                    .addComponent(buttonNum6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonQ)
                    .addComponent(buttonW)
                    .addComponent(buttonE)
                    .addComponent(buttonR)
                    .addComponent(buttonT)
                    .addComponent(buttonY)
                    .addComponent(buttonU)
                    .addComponent(buttonI)
                    .addComponent(buttonO)
                    .addComponent(buttonP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonA)
                    .addComponent(buttonS)
                    .addComponent(buttonD)
                    .addComponent(buttonF)
                    .addComponent(buttonG)
                    .addComponent(buttonH)
                    .addComponent(buttonJ)
                    .addComponent(buttonK)
                    .addComponent(buttonL)
                    .addComponent(buttonEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZ)
                    .addComponent(buttonX)
                    .addComponent(buttonC)
                    .addComponent(buttonV)
                    .addComponent(buttonB)
                    .addComponent(buttonM)
                    .addComponent(buttonN)
                    .addComponent(buttonSpace)
                    .addComponent(buttonShift))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stepButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(powerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debugButton))
                    .addComponent(GPR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GPR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GPR0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GPR3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(debugButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GPR0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GPR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GPR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        powerButton.getAccessibleContext().setAccessibleName("powerbutton");

        pack();
    }
    
    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
        if(!powerButton.isSelected()) {
        	System.out.println("power off");
        	resetAll();
        }
        else {
        	System.out.println("power on");
        	mainCtrl = new Thread(new MainController());
        	mainControl = new Controller();
        	
	        mainControl.initial();
	        mainCtrl.start();
        }
    }

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	//show the content of all registers first.
    	setAll();
    	if(!mainCtrl.isAlive()){
    		stepButton.setEnabled(false);
    		stepButton.setText("End");
    	}
    	//then execute the instruction.
    	mainControl.debugNext = true;
    }

    private void debugButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(debugButton.isSelected()) {
        	mainControl.isDebugModel = true;
        	debugButton.setText("Debug Mode On");
        }
        else {
        	mainControl.isDebugModel = false;
        	debugButton.setText("Debug Mode Off");
        }
    }
    
    private void buttonFActionPerformed(java.awt.event.ActionEvent evt) {                                        
        DevicesINF.characterEnc('f');
        DevicesINF.changeStatus(1);
    }                                       

    private void buttonRActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	DevicesINF.characterEnc('r');
    	DevicesINF.changeStatus(1);
    }                                       

    private void buttonVActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	DevicesINF.characterEnc('v');
    	DevicesINF.changeStatus(1);
    }                                       

    private void buttonNum4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	DevicesINF.characterEnc('4');
    	DevicesINF.changeStatus(1);
    }                                          

    private void buttonNum2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	DevicesINF.characterEnc('2');
    	DevicesINF.changeStatus(1);
    }                                          

    private void buttonShiftActionPerformed(java.awt.event.ActionEvent evt) {
    	//DevicesINF.characterEnc('f');
    }

    private void buttonSpaceActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc(' ');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum1ActionPerformed(java.awt.event.ActionEvent evt) {
        DevicesINF.characterEnc('1');
        DevicesINF.changeStatus(1);
    }

    private void buttonNum3ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('3');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum5ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('5');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum6ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('6');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum7ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('7');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum8ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('8');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum9ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('9');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNum0ActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('0');
    	DevicesINF.changeStatus(1);
    }

    private void buttonQActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('q');
    	DevicesINF.changeStatus(1);
    }

    private void buttonWActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('w');
    	DevicesINF.changeStatus(1);
    }

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('e');
    	DevicesINF.changeStatus(1);
    }

    private void buttonTActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('t');
    	DevicesINF.changeStatus(1);
    }

    private void buttonYActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('y');
    	DevicesINF.changeStatus(1);
    }

    private void buttonUActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('u');
    	DevicesINF.changeStatus(1);
    }

    private void buttonIActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('i');
    	DevicesINF.changeStatus(1);
    }

    private void buttonOActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('o');
    	DevicesINF.changeStatus(1);
    }

    private void buttonPActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('p');
    	DevicesINF.changeStatus(1);
    }

    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('a');
    	DevicesINF.changeStatus(1);
    }

    private void buttonSActionPerformed(java.awt.event.ActionEvent evt) {
        DevicesINF.characterEnc('s');
        DevicesINF.changeStatus(1);
    }

    private void buttonDActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('d');
    	DevicesINF.changeStatus(1);
    }

    private void buttonGActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('g');
    	DevicesINF.changeStatus(1);
    }

    private void buttonHActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('h');
    	DevicesINF.changeStatus(1);
    }

    private void buttonJActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('j');
    	DevicesINF.changeStatus(1);
    }

    private void buttonKActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('k');
    	DevicesINF.changeStatus(1);
    }

    private void buttonLActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('l');
    	DevicesINF.changeStatus(1);
    }

    private void buttonZActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('z');
    	DevicesINF.changeStatus(1);
    }

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('x');
    	DevicesINF.changeStatus(1);
    }

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('c');
    	DevicesINF.changeStatus(1);
    }

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('b');
    	DevicesINF.changeStatus(1);
    }

    private void buttonNActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('n');
    	DevicesINF.changeStatus(1);
    }

    private void buttonMActionPerformed(java.awt.event.ActionEvent evt) {
    	DevicesINF.characterEnc('m');
    	DevicesINF.changeStatus(1);
    }
    
    private void buttonEnterActionPerformed(java.awt.event.ActionEvent evt) {
        DevicesINF.addEndLine();
        DevicesINF.changeStatus(2);
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel GPR0;
    private javax.swing.JLabel GPR0value;
    private javax.swing.JPanel GPR1;
    private javax.swing.JLabel GPR1value;
    private javax.swing.JPanel GPR2;
    private javax.swing.JLabel GPR2value;
    private javax.swing.JPanel GPR3;
    private javax.swing.JLabel GPR3value;
    private javax.swing.JPanel MAR;
    private javax.swing.JLabel MARvalue;
    private javax.swing.JPanel MBR;
    private javax.swing.JLabel MBRvalue;
    private javax.swing.JPanel PC;
    private javax.swing.JLabel PCvalue;
    private javax.swing.JTextArea Printervalue;
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonD;
    private javax.swing.JButton buttonE;
    private javax.swing.JButton buttonF;
    private javax.swing.JButton buttonG;
    private javax.swing.JButton buttonH;
    private javax.swing.JButton buttonI;
    private javax.swing.JButton buttonJ;
    private javax.swing.JButton buttonK;
    private javax.swing.JButton buttonL;
    private javax.swing.JButton buttonM;
    private javax.swing.JButton buttonN;
    private javax.swing.JButton buttonNum0;
    private javax.swing.JButton buttonNum1;
    private javax.swing.JButton buttonNum2;
    private javax.swing.JButton buttonNum3;
    private javax.swing.JButton buttonNum4;
    private javax.swing.JButton buttonNum5;
    private javax.swing.JButton buttonNum6;
    private javax.swing.JButton buttonNum7;
    private javax.swing.JButton buttonNum8;
    private javax.swing.JButton buttonNum9;
    private javax.swing.JButton buttonO;
    private javax.swing.JButton buttonP;
    private javax.swing.JButton buttonQ;
    private javax.swing.JButton buttonR;
    private javax.swing.JButton buttonS;
    private javax.swing.JToggleButton buttonShift;
    private javax.swing.JButton buttonSpace;
    private javax.swing.JButton buttonEnter;
    private javax.swing.JButton buttonT;
    private javax.swing.JButton buttonU;
    private javax.swing.JButton buttonV;
    private javax.swing.JButton buttonW;
    private javax.swing.JButton buttonX;
    private javax.swing.JButton buttonY;
    private javax.swing.JButton buttonZ;
    private javax.swing.JToggleButton debugButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton powerButton;
    private javax.swing.JPanel printPanel;
    private javax.swing.JButton stepButton;
    // End of variables declaration
    private Controller mainControl;
    private Thread mainCtrl;

    class MainController implements Runnable {
    	public void run() {
	        mainControl.run();
    	}
    }
    
        
}
