/*
 * Created on 2010-10-14, 22:45:00
 * By Yichao Yu
 */

package simulator.console;
import simulator.controller.*;
import simulator.interfaces.*;

/** 
 * Class SimulatorConsole
 * simulator's console UI
 *                          
 * @author Yichao Yu
 * @version 10-15-2010
 * @see simulator.controller
 * @since JDK 1.6
 */
public class SimulatorConsole extends javax.swing.JFrame {
	
	private void resetAll() {
		MARvalue.setText("00000000000000");
		MBRvalue.setText("000000000000000000000000");
        GPR0value.setText("000000000000000000000000");
        GPR1value.setText("000000000000000000000000");
        GPR2value.setText("000000000000000000000000");
        GPR3value.setText("000000000000000000000000");
        PCvalue.setText("000000000000000000000000");
	}
	
	private void setAll() {
		MARvalue.setText(OutregsINF.getMAR().getStr());
        MBRvalue.setText(OutregsINF.getMBR().getStr());
        GPR0value.setText(GrINF.getR0().getStr());
        GPR1value.setText(GrINF.getR1().getStr());
        GPR2value.setText(GrINF.getR2().getStr());
        GPR3value.setText(GrINF.getR3().getStr());
        PCvalue.setText(PcINF.getPc().getStr());
	}
	
    /** Creates new form SimulatorConsole */
    public SimulatorConsole() {
        initComponents();
        resetAll();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        powerButton = new javax.swing.JToggleButton();
        stepButton = new javax.swing.JButton();
        MAR = new javax.swing.JPanel();
        MARvalue = new javax.swing.JLabel();
        MBR = new javax.swing.JPanel();
        MBRvalue = new javax.swing.JLabel();
        GPR0 = new javax.swing.JPanel();
        GPR0value = new javax.swing.JLabel();
        GPR1 = new javax.swing.JPanel();
        GPR1value = new javax.swing.JLabel();
        GPR2 = new javax.swing.JPanel();
        GPR2value = new javax.swing.JLabel();
        GPR3 = new javax.swing.JPanel();
        GPR3value = new javax.swing.JLabel();
        debugButton = new javax.swing.JToggleButton();
        PC = new javax.swing.JPanel();
        PCvalue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        powerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("off.png"))); // NOI18N
        powerButton.setRolloverEnabled(false);
        powerButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("on.png"))); // NOI18N
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });

        stepButton.setText("STEP");
        stepButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        MAR.setBorder(javax.swing.BorderFactory.createTitledBorder("MAR"));

        MARvalue.setText("00000000000000");

        javax.swing.GroupLayout MARLayout = new javax.swing.GroupLayout(MAR);
        MAR.setLayout(MARLayout);
        MARLayout.setHorizontalGroup(
            MARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MARLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MARvalue, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        MARLayout.setVerticalGroup(
            MARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MARLayout.createSequentialGroup()
                .addComponent(MARvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MBR.setBorder(javax.swing.BorderFactory.createTitledBorder("MBR"));

        MBRvalue.setText("000000000000000000000000");

        javax.swing.GroupLayout MBRLayout = new javax.swing.GroupLayout(MBR);
        MBR.setLayout(MBRLayout);
        MBRLayout.setHorizontalGroup(
            MBRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MBRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MBRvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MBRLayout.setVerticalGroup(
            MBRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MBRLayout.createSequentialGroup()
                .addComponent(MBRvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR0.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 0"));

        GPR0value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR0Layout = new javax.swing.GroupLayout(GPR0);
        GPR0.setLayout(GPR0Layout);
        GPR0Layout.setHorizontalGroup(
            GPR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR0value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR0Layout.setVerticalGroup(
            GPR0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR0Layout.createSequentialGroup()
                .addComponent(GPR0value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR1.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 1"));

        GPR1value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR1Layout = new javax.swing.GroupLayout(GPR1);
        GPR1.setLayout(GPR1Layout);
        GPR1Layout.setHorizontalGroup(
            GPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR1value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR1Layout.setVerticalGroup(
            GPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR1Layout.createSequentialGroup()
                .addComponent(GPR1value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR2.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 2"));

        GPR2value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR2Layout = new javax.swing.GroupLayout(GPR2);
        GPR2.setLayout(GPR2Layout);
        GPR2Layout.setHorizontalGroup(
            GPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR2value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR2Layout.setVerticalGroup(
            GPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR2Layout.createSequentialGroup()
                .addComponent(GPR2value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GPR3.setBorder(javax.swing.BorderFactory.createTitledBorder("General Purpose Register 3"));

        GPR3value.setText("000000000000000000000000");

        javax.swing.GroupLayout GPR3Layout = new javax.swing.GroupLayout(GPR3);
        GPR3.setLayout(GPR3Layout);
        GPR3Layout.setHorizontalGroup(
            GPR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPR3value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GPR3Layout.setVerticalGroup(
            GPR3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPR3Layout.createSequentialGroup()
                .addComponent(GPR3value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        debugButton.setText("Debug Mode Off");
        debugButton.setBorder(null);
        debugButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        debugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugButtonActionPerformed(evt);
            }
        });

        PC.setBorder(javax.swing.BorderFactory.createTitledBorder("PC"));

        PCvalue.setText("000000000000000000000000");

        javax.swing.GroupLayout PCLayout = new javax.swing.GroupLayout(PC);
        PC.setLayout(PCLayout);
        PCLayout.setHorizontalGroup(
            PCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PCLayout.setVerticalGroup(
            PCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCLayout.createSequentialGroup()
                .addComponent(PCvalue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stepButton, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(powerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GPR3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPR2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPR0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MBR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(465, 465, 465))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(debugButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GPR0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GPR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GPR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        powerButton.getAccessibleContext().setAccessibleName("powerbutton");

        pack();
    }// </editor-fold>

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
        if(!powerButton.isSelected()) {
        	System.out.println("power off");
        	resetAll();
        }
        else {
        	System.out.println("power on");
	        mainControl.initial();
	        mainControl.run();
        }
    }

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	//show the content of all registers first.
    	setAll();
    	//then execute the instruction.
    	mainControl.debugNext = true;
    }

    private void debugButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(debugButton.isSelected()) {
        	mainControl.isDebugModel = true;
        	debugButton.setText("Debug Mode On");
        }
        else {
        	mainControl.isDebugModel = false;
        	debugButton.setText("Debug Mode Off");
        }
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel GPR0;
    private javax.swing.JLabel GPR0value;
    private javax.swing.JPanel GPR1;
    private javax.swing.JLabel GPR1value;
    private javax.swing.JPanel GPR2;
    private javax.swing.JLabel GPR2value;
    private javax.swing.JPanel GPR3;
    private javax.swing.JLabel GPR3value;
    private javax.swing.JPanel MAR;
    private javax.swing.JLabel MARvalue;
    private javax.swing.JPanel MBR;
    private javax.swing.JLabel MBRvalue;
    private javax.swing.JLabel MBRvalue1;
    private javax.swing.JPanel PC;
    private javax.swing.JLabel PCvalue;
    private javax.swing.JToggleButton debugButton;
    private javax.swing.JToggleButton powerButton;
    private javax.swing.JButton stepButton;
    // End of variables declaration
    private static Controller mainControl = new Controller();

    
}
